- app/models/exercise.rb
- app/models/user.rb
finished adding associations to models
> finished adding associations to models

- app/views/shared/_navbar.html.erb
added links to navbar (link to dashboard, blinking exercises, resources, and settings)
> added links to navbar

- db/seeds.rb
finished exercise seeds, 4 exercises
> finished exercise seeds

- app/controllers/exercises_controller.rb
- app/views/exercises/index.html.erb
updated exercises controller with index method and also index.html.erb
> updated exercises controller with index method and also index.html.erb

- app/models/user.rb
added default settings to every new user that is created
> added default settings to every new user that is created

- app/controllers/pages_controller.rb
- app/javascript/components/eye_break_notification.js
- app/javascript/packs/dashboard_on_desktop.js
- app/models/user.rb
- app/views/layouts/application.html.erb
- app/views/pages/desktop_dashboard.html.erb
- app/views/pages/desktop_home.html.erb
- app/views/pages/home.html.erb
- app/views/pages/mobile_dashboard.html.erb
- app/views/pages/mobile_home.html.erb
- public/offline.html
Seperated layouts for desktop and mobile
Added notifications on desktop only, when eye_break_notification_active is true for the current_user
> Eye break notification

- app/views/resources/index.html.erb
finished typing basic info and eye hygiene for resources
> finished typing basic info and eye hygiene for resources

- app/javascript/components/modal.js
- app/javascript/components/timer.js
- app/javascript/packs/application.js
- app/models/user.rb
- app/views/exercises/index.html.erb
- app/views/pages/mobile_dashboard.html.erb
- app/views/resources/index.html.erb
- db/seeds.rb
The html for resources content (content and title, not summary) is in app/javascript/components/modal.js
> Modals for resources

- lib/tasks/routine.rake
changed seconds for exercises from 5 to 60
> changed seconds for exercises from 5 to 60

- app/controllers/application_controller.rb
- app/javascript/packs/application.js
- app/javascript/plugins/init_autocomplete.js
- app/views/devise/registrations/new.html.erb
- db/migrate/20200305185312_add_city_to_users.rb
- db/schema.rb
- package.json
- yarn.lock
Migration to add the column
Update of signup
And autocomplete for city in signup
> Adding city for users

- Gemfile
- Gemfile.lock
- app/controllers/routines_controller.rb
- app/mailers/application_mailer.rb
- app/mailers/user_mailer.rb
- app/views/user_mailer/morning_notification.html.erb
- app/views/user_mailer/night_notification.html.erb
- app/views/user_mailer/welcome.html.erb
- app/views/user_mailer/welcome.text.erb
- config/environments/development.rb
- lib/tasks/routine.rake
- test/mailers/previews/user_mailer_preview.rb
- test/mailers/user_mailer_test.rb
finished email notifications for morning and night exercise
> finished email notifications for morning and night exercise

- app/javascript/components/tabs_navigation.js
- app/javascript/packs/dashboard_on_desktop.js
- app/views/pages/desktop_dashboard.html.erb
modified tabs with correct names for desktop dashboard
> modified tabs with correct names for desktop dashboard

- app/javascript/components/eye_break_notification.js
- app/javascript/packs/dashboard_on_desktop.js
The button should be to put on desktop dashboard with id demo-trigger-button
> Created the trigger JS eye break notif 

- app/javascript/components/modal_exercises.js
- app/views/pages/mobile_dashboard.html.erb
Putting audio back to start and button back to play button
For routine: turned the routine to completed
> Dealing with finished audio

- app/controllers/routines_controller.rb
- app/mailers/user_mailer.rb
- app/services/recommendation.rb
- config/environments/development.rb
- config/environments/production.rb
- config/initializers/smtp.rb
- config/routes.rb
- db/seeds.rb
- lib/tasks/routine.rake
Finished method for generating reps based on weather
> Generate method for weather

- app/controllers/routines_controller.rb
- app/services/recommendation.rb
searching any city in the weather api now works
> searching any city in the weather api now works

- app/assets/stylesheets/components/_banner_mobile.scss
- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_titles.scss
- app/assets/stylesheets/config/_fonts.scss
- app/views/exercises/index.html.erb
Finished the Blink header/banner on mobile registered page
Made the components for titles (orange underline)
Started working on exercise cards
> Exercise cards on index and more

- app/assets/stylesheets/components/_cards.scss
- app/javascript/components/modal_exercises.js
- app/javascript/packs/application.js
- app/views/pages/desktop_dashboard.html.erb
- app/views/pages/mobile_dashboard.html.erb
refactored js code for that and checked that everything still
> Added a play button on routine card

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_form.scss
- app/views/exercises/index.html.erb
- app/views/pages/_desktop_login.html.erb
- app/views/pages/_mobile_login.html.erb
- app/views/pages/desktop_dashboard.html.erb
- app/views/pages/desktop_signup.html.erb
- app/views/pages/mobile_dashboard.html.erb
- app/views/pages/mobile_signup.html.erb
- app/views/resources/index.html.erb
- app/views/shared/_desktoptabs.html.erb
- app/views/shared/_navbar.html.erb
Both on desktop and mobile
- added links to landing page on login and signup pages
- deleted signup link on signup page and login link on login page
- fixed layouts on forms
> Design on unregistered design

- app/javascript/components/modal_exercises.js
- app/javascript/packs/application.js
> fixed precompiling

- app/assets/stylesheets/components/_background_desktop.scss
- app/views/exercises/index.html.erb
- app/views/pages/_desktop_login.html.erb
- app/views/pages/_mobile_login.html.erb
- app/views/pages/desktop_dashboard.html.erb
- app/views/pages/desktop_home.html.erb
- app/views/pages/desktop_signup.html.erb
- app/views/pages/mobile_dashboard.html.erb
- app/views/pages/mobile_home.html.erb
- app/views/pages/mobile_signup.html.erb
- app/views/resources/index.html.erb
- app/views/settings/edit.html.erb
Background no repeat
Size 100%
> Made background work on every device

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_form.scss
- app/views/pages/mobile_signup.html.erb
Moved signup button up on mobile
Made forms the same width on mobile
> Polishing mobile forms

- app/views/user_mailer/morning_notification.html.erb
- app/views/user_mailer/night_notification.html.erb
- config/environments/development.rb
- config/environments/production.rb
changed evening notification and made email banner display in sent emails
> made necessary changes to make email work

- app/javascript/components/modal_exercises.js.erb
- app/views/exercises/index.html.erb
For some reason, it had disappeared! But it is back
> Play button on exercise modal
